version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "C:/laragon/www/CarlosGaribaldi:/var/www/html"
    networks:
      - app-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistemaescolar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Aquí se añade el volumen
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
